### PR TITLE
Do not delete the run dir.

### PR DESCRIPTION
**Pull request by joaomcteixeira**
I know it is very boring to be deleting folders when we are running tests, but it is just too dangerous to have haddock3 deleting folders without asking.

### CODE REVIEW

**Review by amjjbonvin — APPROVED** [review]

**Comment by rvhonorato** [comment]
Any opposition to have a `--force` option?

**Comment by joaomcteixeira** [comment]
I would say we may forget to `--force` option turned on, or go by inertia giving `--force` all the time, as it happens for other software. You can always do `rm -r rundir1 && haddock ...cfg`. I really vote *no* for the `--force`.

**Comment by rvhonorato** [comment]
you are the boss!

**Review by rvhonorato — APPROVED** [review]

**Comment by rvhonorato** [comment]
What is missing in this one?

**Comment by joaomcteixeira** [comment]
Nothing. I was just waiting because we are in very active development of the modules themselves so I thought merging it now would hinder more than help. But if that is not the case, go ahead and merge it. :+1:

**Comment by rvhonorato** [comment]
> You can always do rm -r rundir1 && haddock

😉

**Comment by joaomcteixeira** [comment]
Answering your question @rvhonorato about the fork, you can actually use `--restart 0`. It will do the same as the `--force`.

**Pull request merged**
