### PR TITLE
modules prefix to defaults

### PR DESCRIPTION
**Pull request by joaomcteixeira**
You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and you comply with the following criteria:

- [x] You have stick to Python. Talk with us before adding other programming languages to HADDOCK3
- [ ] Your PR is about CNS
- [x] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [x] You structured the code into small functions as much as possible. You can use classes if there's a (state) purpose
- [x] code follows our coding style
- [x] You wrote tests for the new code
- [x] `tox` tests pass. *Run `tox` command inside the repository folder*
- [x] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [x] PR does not add any *install dependencies* unless permission granted by the HADDOCK team
- [x] PR does not break licensing
- [ ] Your PR is about writing documentation for already existing code :fire:
- [ ] Your PR is about writing tests for already existing code :godmode:

---

#378 broke `--restart` option for some cases.
Corrects and updates definitions for module's folders numeric prefix.

### CODE REVIEW

**Review by douweschulte — APPROVED** [review]
Nice refactor, and especially nice to tell what kind of selection language is used ;-).
One minor point constants are usually written in all caps. But I am not sure if this style is followed in Haddock.

**Comment by joaomcteixeira** [comment]
Usually, in Python, nothing is written `ALL_CAPS`. Sometimes global variables are written that way for clarity. Normally, I only write ALLCAPS for variables that will be used inside functions directly from globals. otherwise, always lower case.

**Comment by douweschulte** [comment]
Okay fine then. In most other languages (and according to PEP8) this is thing, and I do like the fact that this creates immediate recognisability. But please stick to the Haddock code formatting. Local consistency is more important.

**Comment by joaomcteixeira** [comment]
I might need to review all that consistency. Maybe I am wrong. Thanks for pointing it out!

**Pull request merged**
