### PR TITLE
Make the table sortable(Use a React component in libplots)

### PR DESCRIPTION
**Pull request by SarahAlidoost**
You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and that you comply with the following criteria:

- [x] You have sticked to Python. Please talk to us before adding other programming languages to HADDOCK3
- ~~[ ] Your PR is about CNS~~
- [x] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [x] You structured the code into small functions as much as possible. You can use classes if there is a (state) purpose
- [x] Your code follows our coding style
- ~~[ ] You wrote tests for the new code~~
- [x] `tox` tests pass. *Run `tox` command inside the repository folder*
- [x] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [x] PR does not add any dependencies, unless permission granted by the HADDOCK team
- [x] PR does not break licensing
- ~~[ ] Your PR is about writing documentation for already existing code :fire:~~
- ~~[ ] Your PR is about writing tests for already existing code :godmode:~~

---

As discussed before, it is not possible to create a srotable table with pandas or plotly. Instead, we created a React component that does this, see https://github.com/i-VRESSE/haddock3-analysis-components. In this pull request, changes are introduced to use the React component inside the HTML report code. Please run the `haddock3-analyse` command and inspect the `report.html` file. The headers in the table have a sort icon now.

### CODE REVIEW

**Comment by SarahAlidoost** [comment]
@mgiulini Could you please review this pull request and let me know if something is unclear? Thanks

**Review by mgiulini — APPROVED** [review]
Looks good to me!

**Comment by SarahAlidoost** [comment]
@rvhonorato can we merge this pull request?

**Comment by mgiulini** [comment]
> @rvhonorato can we merge this pull request?

rodrigo is on holiday, I will merge it!

**Pull request merged**
