### PR TITLE
Implement `alascan` module

### PR DESCRIPTION
**Pull request by rvhonorato**
🚧  🚧  🚧  🚧  🚧

### CODE REVIEW

**Comment by joaomcteixeira** [comment]
Very cool :dark_sunglasses: 

 I haven't seen in detail the PR yet, but think if it is really needed that `alascan` be a CNS module. Maybe it is best to have a module to create PDBs with `Ala` (that is a module that does the ala mutations) and then the `rigidbody` takes over. Think always in "one module one task" paradigm.

:rocket:

**Comment by amjjbonvin** [comment]
For ala scanning it would be more a refinement scenario (e.g. flexref, mdref, emref and combinations there of)

**Comment by rvhonorato** [comment]
> Very cool 🕶️
> 
> I haven't seen in detail the PR yet, but think if it is really needed that `alascan` be a CNS module. Maybe it is best to have a module to create PDBs with `Ala` (that is a module that does the ala mutations) and then the `rigidbody` takes over. Think always in "one module one task" paradigm.
> 
> 🚀

one module = `alascan` = one task = `alanine scanning` 😉

**Comment by rvhonorato** [comment]
Closing this since it was just an experiment of possibilities, not really code to be used anywhere.

**Comment by amjjbonvin** [comment]
I would implement it as an analysis module - it is nice and useful!

**Comment by joaomcteixeira** [comment]
I thought was a good prototype also. Definitively the idea is very good. I restored the branch. There's no need to delete, if we want to recover that code in the future it is there in the branch.

**Pull request closed without merging**
