### PR TITLE
Add cluster information in `PDBobject`

### LINKED ISSUE #243: Add cluster information to `PDBobject`
`clustfcc` will produce the conventional `cluster.out` but this information is not kept in the pdb object across the modules. It would be beneficial for it to be added as a propriety of the object. This would also simplify `seletopclust`.

### PR DESCRIPTION
**Pull request by rvhonorato**
This PR closes #243 by adding the following to `libontology`
```python
        self.clt_id = None
        self.clt_rank = None
        self.clt_model_rank = None
```
* * *
And since @amjjbonvin commented that:
> It would also be handy to have the output saved on file.

I used the information to write a detailed version of `cluster.out` named `clustfcc.txt` (both are written)

### `cluster.out`
```
Cluster 1 -> 17 3 8 9 11 12 14 16 18 24 26 29 35 37 38 48 62 73 77 78 79 83 84 
Cluster 2 -> 74 10 31 82 86 93 98 
Cluster 3 -> 85 5 7 40 81 95 
Cluster 4 -> 80 6 28 33 50 
Cluster 5 -> 61 41 45 49 71 
Cluster 6 -> 44 15 32 39 43 
Cluster 7 -> 2 53 55 57 58 
Cluster 8 -> 59 64 66 67 
```

### `clustfcc.txt`

```
### clustfcc output ###

Clustering parameters 
> contact_distance_cutoff=5.0A
> fraction_cutoff=0.6
> threshold=4
> strictness=0.75
-----------------------------------------------

Total # of clusters: 8

-----------------------------------------------
Cluster 1 (#1, n=22, top4_avg_score = -32.24)

clt_rank	model_name	score
1	rigidbody_62.pdb	-32.87
2	rigidbody_12.pdb	-32.42
3	rigidbody_24.pdb	-32.29
4	rigidbody_29.pdb	-31.37
5	rigidbody_48.pdb	-30.58
6	rigidbody_26.pdb	-29.89
7	rigidbody_14.pdb	-28.42
8	rigidbody_38.pdb	-27.90
9	rigidbody_3.pdb	-27.30
10	rigidbody_79.pdb	-26.91
11	rigidbody_16.pdb	-26.68
12	rigidbody_11.pdb	-26.49
13	rigidbody_9.pdb	-25.78
14	rigidbody_78.pdb	-24.50
15	rigidbody_37.pdb	-24.21
16	rigidbody_73.pdb	-23.10
17	rigidbody_84.pdb	-22.29
18	rigidbody_8.pdb	-21.98
19	rigidbody_77.pdb	-21.98
20	rigidbody_35.pdb	-21.70
21	rigidbody_18.pdb	-17.53
22	rigidbody_83.pdb	-14.61

-----------------------------------------------
Cluster 2 (#3, n=5, top4_avg_score = -25.87)

clt_rank	model_name	score
1	rigidbody_81.pdb	-27.58
2	rigidbody_40.pdb	-27.37
3	rigidbody_5.pdb	-24.34
4	rigidbody_95.pdb	-24.18
5	rigidbody_7.pdb	-24.13

-----------------------------------------------
Cluster 3 (#7, n=4, top4_avg_score = -20.86)

clt_rank	model_name	score
1	rigidbody_55.pdb	-21.96
2	rigidbody_58.pdb	-21.77
3	rigidbody_57.pdb	-20.88
4	rigidbody_53.pdb	-18.81

-----------------------------------------------
Cluster 4 (#6, n=4, top4_avg_score = -19.53)

clt_rank	model_name	score
1	rigidbody_32.pdb	-21.78
2	rigidbody_39.pdb	-21.13
3	rigidbody_15.pdb	-19.00
4	rigidbody_43.pdb	-16.22

-----------------------------------------------
Cluster 5 (#2, n=6, top4_avg_score = -18.54)

clt_rank	model_name	score
1	rigidbody_98.pdb	-21.78
2	rigidbody_93.pdb	-19.51
3	rigidbody_31.pdb	-16.60
4	rigidbody_10.pdb	-16.27
5	rigidbody_86.pdb	-13.71
6	rigidbody_82.pdb	-10.85

-----------------------------------------------
Cluster 6 (#4, n=4, top4_avg_score = -14.06)

clt_rank	model_name	score
1	rigidbody_6.pdb	-16.44
2	rigidbody_33.pdb	-15.37
3	rigidbody_28.pdb	-13.90
4	rigidbody_50.pdb	-10.54

-----------------------------------------------
Cluster 7 (#5, n=4, top4_avg_score = -13.42)

clt_rank	model_name	score
1	rigidbody_71.pdb	-15.95
2	rigidbody_41.pdb	-12.80
3	rigidbody_49.pdb	-12.65
4	rigidbody_45.pdb	-12.28

-----------------------------------------------
Cluster 8 (#8, n=3, top4_avg_score = -13.25)

clt_rank	model_name	score
1	rigidbody_66.pdb	-22.29
2	rigidbody_67.pdb	-16.65
3	rigidbody_64.pdb	-14.06
-----------------------------------------------
```

### CODE REVIEW

**Comment by rvhonorato** [comment]
Just noticed that even with `threshold=4`, cluster 8 in the example above only has 3 elements since I am not considering the cluster center for this detailed output.

Should it also be included as an element - ie: in the list with the other models or as information, below the "header" line? 
```
Cluster 8 (#8, n=3, top4_avg_score = -13.25)
```

**Comment by amjjbonvin** [comment]
You should consider the top4 ranked models of the cluster when calculating the average score - and also any cluster-based selection should be based on the score (for consistency with 2.4)

**Comment by rvhonorato** [comment]
> You should consider the top4 ranked models of the cluster when calculating the average score - and also any cluster-based selection should be based on the score (for consistency with 2.4)

I know, this is how its being done here.

**Comment by rvhonorato** [comment]
> but what is then the issue with the cluster center? And N=3?

Is the cluster center included in the calculations/results or is it just used to anchor the clustering and can be ignored?

**Comment by amjjbonvin** [comment]
It can be ignored since we select on the haddock score

**Comment by rvhonorato** [comment]
> It can be ignored since we select on the haddock score

Ok!

> but what is then the issue with the cluster center? And N=3?

Here I ran with threshold=4 and got this on cluster.out, so I guess the threshold includes the center
`Cluster 8 -> 59 64 66 67`

**Comment by rvhonorato** [comment]
Changed it so that the detailed `clusterfcc.txt` also highlights what are the cluster centers, but the centers will NOT be passed to the next module, is that correct?

```
-----------------------------------------------
Cluster 8 (#8, n=4, top4_avg_score = -16.76)

clt_rank	model_name	score
1	rigidbody_66.pdb	-22.29
2	rigidbody_67.pdb	-16.65
3	rigidbody_64.pdb	-14.06
4	rigidbody_59.pdb	-14.03	*
-----------------------------------------------
```

**Comment by amjjbonvin** [comment]
Yes - correct behaviour

**Review by amjjbonvin — APPROVED** [review]
Nice and informative output!

**Review by joaomcteixeira — APPROVED** [review]
Some of the changes here are repeated in #248 (for example in `clustfcc`), be mindful of that when merging. Aside from that, everything very nice! :rocket:

**Pull request merged**
