### PR TITLE
Change log statements

### PR DESCRIPTION
**Pull request by rvhonorato**
I changed the log statements so it display information that is more relevant to the way we usually look at the HADDOCK execution (also more in line with what we are using in 2.x).

I also made it display the % of completion, this is how it looks now with this PR.

```text
[2021-11-28 15:50:03,299 cli INFO] 
##############################################
#                                            #
#                 HADDOCK 3                  #
#                                            #
##############################################

Starting HADDOCK 3.0.0 on 2021-11-28 15:50:00

Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:54:06) 
[Clang 11.0.0 ]

[2021-11-28 15:50:05,623 libutil WARNING] /Users/rodrigo/repos/haddock3/examples/docking-protein-protein/run1 exists and it will be REMOVED!
[2021-11-28 15:50:05,663 libworkflow INFO] Reading instructions of [topoaa] step
[2021-11-28 15:50:05,663 libworkflow INFO] Reading instructions of [rigidbody] step
[2021-11-28 15:50:05,663 libworkflow INFO] Reading instructions of [caprieval] step
[2021-11-28 15:50:05,663 libworkflow INFO] Reading instructions of [seletop] step
[2021-11-28 15:50:05,664 libworkflow INFO] Reading instructions of [flexref] step
[2021-11-28 15:50:05,664 libworkflow INFO] Reading instructions of [caprieval.1] step
[2021-11-28 15:50:05,664 libworkflow INFO] Reading instructions of [emref] step
[2021-11-28 15:50:05,665 libworkflow INFO] Reading instructions of [caprieval.2] step
[2021-11-28 15:50:05,670 __init__ INFO] Running [topoaa] module
[2021-11-28 15:50:05,671 __init__ INFO] [topoaa] Generating topologies
[2021-11-28 15:50:05,671 __init__ INFO] [topoaa] Molecule 1: e2aP_1F3G.pdb
[2021-11-28 15:50:05,678 __init__ INFO] [topoaa] Sanitizing molecule e2aP_1F3G.pdb
[2021-11-28 15:50:05,696 __init__ INFO] [topoaa] CNS input created at 00_topoaa/e2aP_1F3G.inp
[2021-11-28 15:50:05,696 __init__ INFO] [topoaa] Molecule 2: hpr_ensemble.pdb
[2021-11-28 15:50:05,725 __init__ INFO] [topoaa] Sanitizing molecule hpr_ensemble_1.pdb
[2021-11-28 15:50:05,752 __init__ INFO] [topoaa] CNS input created at 00_topoaa/hpr_ensemble_1.inp
[2021-11-28 15:50:05,753 __init__ INFO] [topoaa] Sanitizing molecule hpr_ensemble_10.pdb
[2021-11-28 15:50:05,765 __init__ INFO] [topoaa] CNS input created at 00_topoaa/hpr_ensemble_10.inp
[2021-11-28 15:50:05,765 __init__ INFO] [topoaa] Sanitizing molecule hpr_ensemble_2.pdb
[2021-11-28 15:50:05,777 __init__ INFO] [topoaa] CNS input created at 00_topoaa/hpr_ensemble_2.inp
[2021-11-28 15:50:05,777 __init__ INFO] [topoaa] Sanitizing molecule hpr_ensemble_3.pdb
[2021-11-28 15:50:05,790 __init__ INFO] [topoaa] CNS input created at 00_topoaa/hpr_ensemble_3.inp
[2021-11-28 15:50:05,790 __init__ INFO] [topoaa] Sanitizing molecule hpr_ensemble_4.pdb
[2021-11-28 15:50:05,805 __init__ INFO] [topoaa] CNS input created at 00_topoaa/hpr_ensemble_4.inp
[2021-11-28 15:50:05,806 __init__ INFO] [topoaa] Sanitizing molecule hpr_ensemble_5.pdb
[2021-11-28 15:50:05,820 __init__ INFO] [topoaa] CNS input created at 00_topoaa/hpr_ensemble_5.inp
[2021-11-28 15:50:05,821 __init__ INFO] [topoaa] Sanitizing molecule hpr_ensemble_6.pdb
[2021-11-28 15:50:05,829 __init__ INFO] [topoaa] CNS input created at 00_topoaa/hpr_ensemble_6.inp
[2021-11-28 15:50:05,829 __init__ INFO] [topoaa] Sanitizing molecule hpr_ensemble_7.pdb
[2021-11-28 15:50:05,840 __init__ INFO] [topoaa] CNS input created at 00_topoaa/hpr_ensemble_7.inp
[2021-11-28 15:50:05,841 __init__ INFO] [topoaa] Sanitizing molecule hpr_ensemble_8.pdb
[2021-11-28 15:50:05,851 __init__ INFO] [topoaa] CNS input created at 00_topoaa/hpr_ensemble_8.inp
[2021-11-28 15:50:05,852 __init__ INFO] [topoaa] Sanitizing molecule hpr_ensemble_9.pdb
[2021-11-28 15:50:05,863 __init__ INFO] [topoaa] CNS input created at 00_topoaa/hpr_ensemble_9.inp
[2021-11-28 15:50:05,863 __init__ INFO] [topoaa] Running CNS engine with 11 jobs
[2021-11-28 15:50:08,896 libparallel INFO] < Starting 00_topoaa/hpr_ensemble_1.inp
[2021-11-28 15:50:08,915 libparallel INFO] < Starting 00_topoaa/hpr_ensemble_10.inp
[2021-11-28 15:50:10,547 libparallel INFO] < Starting 00_topoaa/e2aP_1F3G.inp
[2021-11-28 15:50:10,903 libparallel INFO] < Starting 00_topoaa/hpr_ensemble_3.inp
[2021-11-28 15:50:10,944 libparallel INFO] < Starting 00_topoaa/hpr_ensemble_4.inp
[2021-11-28 15:50:12,419 libparallel INFO] < Starting 00_topoaa/hpr_ensemble_2.inp
[2021-11-28 15:50:12,767 libparallel INFO] < Starting 00_topoaa/hpr_ensemble_6.inp
[2021-11-28 15:50:12,784 libparallel INFO] < Starting 00_topoaa/hpr_ensemble_7.inp
[2021-11-28 15:50:14,110 libparallel INFO] < Starting 00_topoaa/hpr_ensemble_5.inp
[2021-11-28 15:50:14,582 libparallel INFO] < Starting 00_topoaa/hpr_ensemble_9.inp
[2021-11-28 15:50:15,490 libparallel INFO] < Starting 00_topoaa/hpr_ensemble_8.inp
[2021-11-28 15:50:15,504 libparallel INFO] >> 00_topoaa/e2aP_1F3G.inp completed 9% 
[2021-11-28 15:50:15,506 libparallel INFO] >> 00_topoaa/hpr_ensemble_2.inp completed 18% 
[2021-11-28 15:50:15,507 libparallel INFO] >> 00_topoaa/hpr_ensemble_5.inp completed 27% 
[2021-11-28 15:50:15,507 libparallel INFO] >> 00_topoaa/hpr_ensemble_8.inp completed 36% 
[2021-11-28 15:50:15,507 libparallel INFO] >> 00_topoaa/hpr_ensemble_1.inp completed 45% 
[2021-11-28 15:50:15,507 libparallel INFO] >> 00_topoaa/hpr_ensemble_3.inp completed 55% 
[2021-11-28 15:50:15,507 libparallel INFO] >> 00_topoaa/hpr_ensemble_6.inp completed 64% 
[2021-11-28 15:50:15,507 libparallel INFO] >> 00_topoaa/hpr_ensemble_9.inp completed 73% 
[2021-11-28 15:50:15,507 libparallel INFO] >> 00_topoaa/hpr_ensemble_10.inp completed 82% 
[2021-11-28 15:50:15,507 libparallel INFO] >> 00_topoaa/hpr_ensemble_4.inp completed 91% 
[2021-11-28 15:50:15,507 libparallel INFO] >> 00_topoaa/hpr_ensemble_7.inp completed 100% 
[2021-11-28 15:50:15,507 libparallel INFO] 11 tasks finished
[2021-11-28 15:50:15,508 __init__ INFO] [topoaa] CNS engine has finished
[2021-11-28 15:50:15,521 __init__ INFO] Module [topoaa] finished
[2021-11-28 15:50:15,539 __init__ INFO] Running [rigidbody] module
[2021-11-28 15:50:15,578 __init__ INFO] [rigidbody] Running CNS engine with 20 jobs
[2021-11-28 15:50:26,687 libparallel INFO] < Starting 01_rigidbody/rigidbody_2.inp
[2021-11-28 15:50:27,198 libparallel INFO] < Starting 01_rigidbody/rigidbody_1.inp
[2021-11-28 15:50:27,209 libparallel INFO] < Starting 01_rigidbody/rigidbody_3.inp
[2021-11-28 15:50:33,577 libparallel INFO] < Starting 01_rigidbody/rigidbody_6.inp
[2021-11-28 15:50:35,589 libparallel INFO] < Starting 01_rigidbody/rigidbody_4.inp
[2021-11-28 15:50:35,910 libparallel INFO] < Starting 01_rigidbody/rigidbody_5.inp
[2021-11-28 15:50:43,448 libparallel INFO] < Starting 01_rigidbody/rigidbody_7.inp
[2021-11-28 15:50:44,067 libparallel INFO] < Starting 01_rigidbody/rigidbody_9.inp
[2021-11-28 15:50:44,639 libparallel INFO] < Starting 01_rigidbody/rigidbody_8.inp
[2021-11-28 15:50:50,952 libparallel INFO] < Starting 01_rigidbody/rigidbody_12.inp
[2021-11-28 15:50:51,048 libparallel INFO] < Starting 01_rigidbody/rigidbody_10.inp
[2021-11-28 15:50:52,078 libparallel INFO] < Starting 01_rigidbody/rigidbody_11.inp
[2021-11-28 15:50:57,338 libparallel INFO] < Starting 01_rigidbody/rigidbody_15.inp
[2021-11-28 15:50:57,599 libparallel INFO] < Starting 01_rigidbody/rigidbody_13.inp
[2021-11-28 15:50:59,123 libparallel INFO] < Starting 01_rigidbody/rigidbody_14.inp
[2021-11-28 15:51:07,293 libparallel INFO] < Starting 01_rigidbody/rigidbody_18.inp
[2021-11-28 15:51:08,793 libparallel INFO] < Starting 01_rigidbody/rigidbody_16.inp
[2021-11-28 15:51:10,269 libparallel INFO] < Starting 01_rigidbody/rigidbody_17.inp
[2021-11-28 15:51:13,940 libparallel INFO] < Starting 01_rigidbody/rigidbody_19.inp
[2021-11-28 15:51:13,951 libparallel INFO] >> 01_rigidbody/rigidbody_1.inp completed 5% 
[2021-11-28 15:51:13,952 libparallel INFO] >> 01_rigidbody/rigidbody_4.inp completed 10% 
[2021-11-28 15:51:13,952 libparallel INFO] >> 01_rigidbody/rigidbody_7.inp completed 15% 
[2021-11-28 15:51:13,952 libparallel INFO] >> 01_rigidbody/rigidbody_10.inp completed 20% 
[2021-11-28 15:51:13,952 libparallel INFO] >> 01_rigidbody/rigidbody_13.inp completed 25% 
[2021-11-28 15:51:13,952 libparallel INFO] >> 01_rigidbody/rigidbody_16.inp completed 30% 
[2021-11-28 15:51:13,952 libparallel INFO] >> 01_rigidbody/rigidbody_19.inp completed 35% 
[2021-11-28 15:51:15,651 libparallel INFO] < Starting 01_rigidbody/rigidbody_20.inp
[2021-11-28 15:51:15,660 libparallel INFO] >> 01_rigidbody/rigidbody_2.inp completed 40% 
[2021-11-28 15:51:15,660 libparallel INFO] >> 01_rigidbody/rigidbody_5.inp completed 45% 
[2021-11-28 15:51:15,660 libparallel INFO] >> 01_rigidbody/rigidbody_8.inp completed 50% 
[2021-11-28 15:51:15,660 libparallel INFO] >> 01_rigidbody/rigidbody_11.inp completed 55% 
[2021-11-28 15:51:15,660 libparallel INFO] >> 01_rigidbody/rigidbody_14.inp completed 60% 
[2021-11-28 15:51:15,660 libparallel INFO] >> 01_rigidbody/rigidbody_17.inp completed 65% 
[2021-11-28 15:51:15,660 libparallel INFO] >> 01_rigidbody/rigidbody_20.inp completed 70% 
[2021-11-28 15:51:15,660 libparallel INFO] >> 01_rigidbody/rigidbody_3.inp completed 75% 
[2021-11-28 15:51:15,661 libparallel INFO] >> 01_rigidbody/rigidbody_6.inp completed 80% 
[2021-11-28 15:51:15,661 libparallel INFO] >> 01_rigidbody/rigidbody_9.inp completed 85% 
[2021-11-28 15:51:15,661 libparallel INFO] >> 01_rigidbody/rigidbody_12.inp completed 90% 
[2021-11-28 15:51:15,661 libparallel INFO] >> 01_rigidbody/rigidbody_15.inp completed 95% 
[2021-11-28 15:51:15,661 libparallel INFO] >> 01_rigidbody/rigidbody_18.inp completed 100% 
[2021-11-28 15:51:15,661 libparallel INFO] 20 tasks finished
[2021-11-28 15:51:15,661 __init__ INFO] [rigidbody] CNS engine has finished
[2021-11-28 15:51:15,800 __init__ INFO] Module [rigidbody] finished
[2021-11-28 15:51:15,807 __init__ INFO] Running [caprieval] module
[2021-11-28 15:51:15,808 __init__ INFO] [caprieval] Calculating CAPRI metrics...
[2021-11-28 15:51:15,808 __init__ INFO] [caprieval] Using data/e2a-hpr_1GGR.pdb as reference structure
[2021-11-28 15:51:17,169 __init__ INFO] [caprieval] Calculating FNAT
[2021-11-28 15:51:17,170 __init__ INFO] [caprieval]  cutoff: 5.0A
[2021-11-28 15:51:17,417 __init__ INFO] [caprieval] Calculating I-RMSD
[2021-11-28 15:51:17,418 __init__ INFO] [caprieval]  cutoff: 10.0A
[2021-11-28 15:51:17,527 __init__ INFO] [caprieval] Calculating L-RMSD
[2021-11-28 15:51:17,527 __init__ INFO] [caprieval]  Receptor chain: A
[2021-11-28 15:51:17,527 __init__ INFO] [caprieval]  Ligand chain: B
[2021-11-28 15:51:17,696 __init__ INFO] [caprieval] Calculating I-L-RMSD
[2021-11-28 15:51:17,696 __init__ INFO] [caprieval]  cutoff: 10.0A
[2021-11-28 15:51:17,696 __init__ INFO] [caprieval]  Ligand chain: B
[2021-11-28 15:51:18,025 __init__ INFO] [caprieval] Saving output to /Users/rodrigo/repos/haddock3/examples/docking-protein-protein/run1/02_caprieval/capri.tsv
[2021-11-28 15:51:18,028 __init__ INFO] Module [caprieval] finished
[2021-11-28 15:51:18,031 __init__ INFO] Running [seletop] module
[2021-11-28 15:51:18,046 __init__ INFO] Running [flexref] module
[2021-11-28 15:51:18,056 __init__ INFO] [flexref] Running CNS engine with 5 jobs
[2021-11-28 15:51:23,395 libparallel INFO] < Starting 04_flexref/flexref_3.inp
[2021-11-28 15:51:23,427 libparallel INFO] < Starting 04_flexref/flexref_1.inp
[2021-11-28 15:51:23,464 libparallel INFO] < Starting 04_flexref/flexref_2.inp
[2021-11-28 15:51:26,575 libparallel INFO] < Starting 04_flexref/flexref_4.inp
[2021-11-28 15:51:26,585 libparallel INFO] >> 04_flexref/flexref_1.inp completed 20% 
[2021-11-28 15:51:26,586 libparallel INFO] >> 04_flexref/flexref_4.inp completed 40% 
[2021-11-28 15:51:26,650 libparallel INFO] < Starting 04_flexref/flexref_5.inp
[2021-11-28 15:51:26,658 libparallel INFO] >> 04_flexref/flexref_2.inp completed 60% 
[2021-11-28 15:51:26,658 libparallel INFO] >> 04_flexref/flexref_5.inp completed 80% 
[2021-11-28 15:51:26,658 libparallel INFO] >> 04_flexref/flexref_3.inp completed 100% 
[2021-11-28 15:51:26,658 libparallel INFO] 5 tasks finished
[2021-11-28 15:51:26,658 __init__ INFO] [flexref] CNS engine has finished
[2021-11-28 15:51:26,665 __init__ INFO] Module [flexref] finished
[2021-11-28 15:51:26,667 __init__ INFO] Running [caprieval] module
[2021-11-28 15:51:26,667 __init__ INFO] [caprieval] Calculating CAPRI metrics...
[2021-11-28 15:51:26,667 __init__ INFO] [caprieval] Using data/e2a-hpr_1GGR.pdb as reference structure
[2021-11-28 15:51:26,944 __init__ INFO] [caprieval] Calculating FNAT
[2021-11-28 15:51:26,944 __init__ INFO] [caprieval]  cutoff: 5.0A
[2021-11-28 15:51:26,999 __init__ INFO] [caprieval] Calculating I-RMSD
[2021-11-28 15:51:27,000 __init__ INFO] [caprieval]  cutoff: 10.0A
[2021-11-28 15:51:27,042 __init__ INFO] [caprieval] Calculating L-RMSD
[2021-11-28 15:51:27,042 __init__ INFO] [caprieval]  Receptor chain: A
[2021-11-28 15:51:27,043 __init__ INFO] [caprieval]  Ligand chain: B
[2021-11-28 15:51:27,083 __init__ INFO] [caprieval] Calculating I-L-RMSD
[2021-11-28 15:51:27,083 __init__ INFO] [caprieval]  cutoff: 10.0A
[2021-11-28 15:51:27,083 __init__ INFO] [caprieval]  Ligand chain: B
[2021-11-28 15:51:27,160 __init__ INFO] [caprieval] Saving output to /Users/rodrigo/repos/haddock3/examples/docking-protein-protein/run1/05_caprieval/capri.tsv
[2021-11-28 15:51:27,161 __init__ INFO] Module [caprieval] finished
[2021-11-28 15:51:27,174 __init__ INFO] Running [emref] module
[2021-11-28 15:51:27,180 __init__ INFO] [emref] Running CNS engine with 5 jobs
[2021-11-28 15:51:32,249 libparallel INFO] < Starting 06_emref/emref_2.inp
[2021-11-28 15:51:32,319 libparallel INFO] < Starting 06_emref/emref_3.inp
[2021-11-28 15:51:32,377 libparallel INFO] < Starting 06_emref/emref_1.inp
[2021-11-28 15:51:35,060 libparallel INFO] < Starting 06_emref/emref_5.inp
[2021-11-28 15:51:35,130 libparallel INFO] < Starting 06_emref/emref_4.inp
[2021-11-28 15:51:35,139 libparallel INFO] >> 06_emref/emref_1.inp completed 20% 
[2021-11-28 15:51:35,140 libparallel INFO] >> 06_emref/emref_4.inp completed 40% 
[2021-11-28 15:51:35,140 libparallel INFO] >> 06_emref/emref_2.inp completed 60% 
[2021-11-28 15:51:35,140 libparallel INFO] >> 06_emref/emref_5.inp completed 80% 
[2021-11-28 15:51:35,140 libparallel INFO] >> 06_emref/emref_3.inp completed 100% 
[2021-11-28 15:51:35,140 libparallel INFO] 5 tasks finished
[2021-11-28 15:51:35,140 __init__ INFO] [emref] CNS engine has finished
[2021-11-28 15:51:35,150 __init__ INFO] Running [caprieval] module
[2021-11-28 15:51:35,151 __init__ INFO] [caprieval] Calculating CAPRI metrics...
[2021-11-28 15:51:35,151 __init__ INFO] [caprieval] Using data/e2a-hpr_1GGR.pdb as reference structure
[2021-11-28 15:51:35,430 __init__ INFO] [caprieval] Calculating FNAT
[2021-11-28 15:51:35,430 __init__ INFO] [caprieval]  cutoff: 5.0A
[2021-11-28 15:51:35,491 __init__ INFO] [caprieval] Calculating I-RMSD
[2021-11-28 15:51:35,491 __init__ INFO] [caprieval]  cutoff: 10.0A
[2021-11-28 15:51:35,541 __init__ INFO] [caprieval] Calculating L-RMSD
[2021-11-28 15:51:35,541 __init__ INFO] [caprieval]  Receptor chain: A
[2021-11-28 15:51:35,541 __init__ INFO] [caprieval]  Ligand chain: B
[2021-11-28 15:51:35,583 __init__ INFO] [caprieval] Calculating I-L-RMSD
[2021-11-28 15:51:35,583 __init__ INFO] [caprieval]  cutoff: 10.0A
[2021-11-28 15:51:35,583 __init__ INFO] [caprieval]  Ligand chain: B
[2021-11-28 15:51:35,668 __init__ INFO] [caprieval] Saving output to /Users/rodrigo/repos/haddock3/examples/docking-protein-protein/run1/07_caprieval/capri.tsv
[2021-11-28 15:51:35,670 __init__ INFO] Module [caprieval] finished
[2021-11-28 15:51:35,670 cli INFO] Finished at 28/11/2021 15:51:35. Good bye! Tot ziens! Até logo!
```

### CODE REVIEW

**Review by amjjbonvin — APPROVED** [review]
This is a small sampling test case. How will the log look like if you run 10000 rigid body models...? Won't it generate too many lines?

**Comment by amjjbonvin** [comment]
```
[2021-11-28 15:51:10,269 libparallel INFO] < Starting 01_rigidbody/rigidbody_17.inp
[2021-11-28 15:51:13,940 libparallel INFO] < Starting 01_rigidbody/rigidbody_19.inp
[2021-11-28 15:51:13,951 libparallel INFO] >> 01_rigidbody/rigidbody_1.inp completed 5% 
[2021-11-28 15:51:13,952 libparallel INFO] >> 01_rigidbody/rigidbody_4.inp completed 10% 
```

Couldn't we combine those lines into something like:
```
[2021-11-28 15:51:10,269 libparallel INFO] < Running 01_rigidbody model 17 - completed  XX out of YYYY - XX%
...
```
Were XX is the total number of models completed so far, YYYY is the sampling, and XX% is the percentage completed?

**Comment by rvhonorato** [comment]
> Couldn't we combine those lines into something like:
> 
> ```
> [2021-11-28 15:51:10,269 libparallel INFO] < Running 01_rigidbody model 17 - completed  XX out of YYYY - XX%
> ...
> ```
> 
> Where XX is the total number of models completed so far, YYYY is the sampling, and XX% is the percentage completed?

That would be better indeed and generate less lines, let me try to change it!

**Comment by joaomcteixeira** [comment]
Do we need all the `[%TIME %MODULE %INFO]` header, or would it be best if we do:

```
> Running [caprieval] module
       * Calculating CAPRI metrics...
       * Using data/e2a-hpr_1GGR.pdb as reference structure
       * Calculating FNAT
          * cutoff: 5.0A
       *Calculating I-RMSD
          * cutoff: 10.0A
```

This log is more user friendly. We could add some minimal `%TIME` time tagging for debugging purposes. I have a couple of classes for this formatting in other projects if you want. We could have the `[%TIME %MODULE %INFO]` if we go `DEBUG` mode. The question of the log is always, at does it serve? sometimes we want logging to provide a nice message for users, others for pure debugging purposes. Sometimes a mix... But that should be clear, otherwise, we end up with loggings ugly for the user and that also add nothing for debug purposes.

It's a suggestion (adding more information for the table), not saying we should adopt this.

**Comment by amjjbonvin** [comment]
This doesn’t add that much additional load and is actually useful info, e.g. where are you in the workflow 
I would keep it.

**Comment by joaomcteixeira** [comment]
Sent a commit with a couple of arch changes in the modules to facilitate log messages for all the modules. We were doing poor use of the OO arch (https://github.com/haddocking/haddock3/pull/159/commits/1f00789fbe41c7e87ce5113c92a5b73bceebc31c). Nothing changes overall, but minor changes do exist if you are implementing new modules. See commit message

**Comment by joaomcteixeira** [comment]
What is missing here?

**Comment by joaomcteixeira** [comment]
Note, merging this will require changing some header parts in `run` method of the modules when solving auto-merge conflicts. I will handle that.

**Comment by rvhonorato** [comment]
Removed the `Starting` so its less verbose, now the % updates on every finished model
```
[2021-11-28 15:51:10,269 libparallel INFO] < Starting 01_rigidbody/rigidbody_17.inp
[2021-11-28 15:51:13,940 libparallel INFO] < Starting 01_rigidbody/rigidbody_19.inp
```

**Comment by rvhonorato** [comment]
Think we can go on @joaomcteixeira, resolve and merge! 🤖

**Comment by rvhonorato** [comment]
Just to complement; it might end up producing a lot of lines but for running with multiprocessing there is no `time.sleep` or `wait` for the models to complete and they are handled internally by python, to replicate the same behavior we get for the batch system in the multiprocessing we need to re-impelement the internal python methods and it will be more inefficient.

**Comment by amjjbonvin** [comment]
Ok - fine as is then :-)

**Pull request merged**
