### PR TITLE
Implements CI for python modules

### LINKED ISSUE #108: Implement GitHub actions CI here
For modules that depend on Python (open) dependencies, we can have their own GitHub actions; CNS-based testing go to private Jenkins. For example:

- GitHub actions using pytest for the general HADDOCK3 Python shell 
- GitHub actions specific for each module that uses thirdparty libraries for which installation via git action does **not** compromise the privacy of the module
- Private Jenkin server to test CNS-based modules.
- Other CI related stuff (version bump, docs, lint, etc) go also in GitHub actions.

Do you agree?

_Originally posted by @joaomcteixeira in https://github.com/haddocking/haddock3/discussions/103#discussioncomment-1563298_

### PR DESCRIPTION
**Pull request by joaomcteixeira**
Implements CI for Python modules that are independent of CNS. Closes #108

Adds to main components of CI:

* testing environment with `tox`
* GitHub actions

`tox` grants an equal environment for testing for all developers with the need to configure anything locally. There are several interesting options implemented:

To test haddock3 python shell in the different python version, run:
* `tox -e py38`
* `tox -e py39`

To see if HADDOCK3 builds properly as a Python package:
* `tox -e build`

To evaluate coding style (lint), code quality (cyclomatic complexity), and safety, run:
* `tox -e lint`
* `tox -e radon`
* `tox -e safety`

CI for documentation has not been added yet. We will add it when we establish the vehicle for documentation.

GitHub actions test for `py38`, `py39`, `build`, and `lint`. We will activate `codecov` reports as part of these actions.

Added `bump2version` for version control - also handled by `tox`.

Version bump and tagging as in [pdb-tools](https://github.com/haddocking/pdb-tools/blob/master/.github/workflows/bump-version-on-push.yml) will be added once we release the first version.

### CODE REVIEW

**Comment by joaomcteixeira** [comment]
I need to open this PR for review to see if the actions run.

**Review by amjjbonvin — APPROVED** [review]
I am not the expert on these actions. I have to trust you.

**Review by rvhonorato — APPROVED** [review]
looks nice!

**Comment by joaomcteixeira** [comment]
@amjjbonvin you don't need o trust :relaxed: I can explain.

I am using `tox` to control the environments for testing. With `tox` we ensure everyone has the same settings and environment when running tests for HADDOCK3. Inside the tox configuration file you define several environments. Basically each env is a series of commands.

If you look for `py38` env inside `tox.ini` you will see that it installs HADDOCK3 in develop mode (exactly what we ask users to do when installing haddock), installs pytest and other needed packages, runs pytest tests and collects coverage reports (that later will be sent to CodeCov).

Other environments test for `lint` and other qualities. You can reproduce all commands manually, but with `tox` everything is defined there.

The GitHub Actions are just reproductions of the tox environments. There is one action for each test: "pytests in python 3.8 -> 3.10" for Linux and MacOS. Also, lint, package building, and version bump (that I will add after we release the first version).

One of the tricky things here is that I need to install FCC also in the actions (for now). Similar to what I define [here](https://github.com/joaomcteixeira/python-project-skeleton/tree/master/.github/workflows).

**Comment by amjjbonvin** [comment]
This should require proper documentation in the installation instruction (for devel mode).

**Comment by joaomcteixeira** [comment]
Added instructions.
Everything is passing in my fork -> https://github.com/joaomcteixeira/haddock3/pull/2
Merging...

**Pull request merged**
