### PR TITLE
Improves Scheduler `ctrl+c` handling

### LINKED ISSUE #96: Better control of Ctrl+c breaks with CNS
A `Ctrl+c` hit when CNS is running is not captured properly by the python shell which may trigger other python-related errors like `FileNotFound`.

### PR DESCRIPTION
**Pull request by joaomcteixeira**
Closes #96 

Now has a controlled exit message for when the user presses `ctrl+c` while `cns` is running. CNS error messages due to `ctrl+c` will be ignored and not printed. CNS error messages should be raised as `CNSRunningError`, as before.

**example:**

```
[2021-10-31 12:19:21,450] haddock.libs.libparallel:L64 INFO - Scheduler configurated for 2 cpu cores.
[2021-10-31 12:19:21,450] haddock.libs.libparallel:L17 INFO - Worker ready with 1 tasks
[2021-10-31 12:19:21,450] haddock.libs.libparallel:L17 INFO - Worker ready with 1 tasks
[2021-10-31 12:19:21,450] haddock.libs.libparallel:L55 INFO - 2 tasks ready.
^C[2021-10-31 12:19:21,819] haddock.libs.libparallel:L80 INFO - You have halted subprocess execution by hitting Ctrl+c
[2021-10-31 12:19:21,819] haddock.libs.libparallel:L89 INFO - The workers terminated in a controlled way
# haddock3 exists here
```

### CODE REVIEW

**Comment by amjjbonvin** [comment]
What if you are running e.g. lightdock? do you still get a message that cns execution has been stopped?

**Comment by joaomcteixeira** [comment]
Sorry, the message does not say `CNS` any more, I forgot to update the description after the last commit (https://github.com/haddocking/haddock3/pull/105/commits/ad156e8fad44a4317bf2c90fa556eacb2a8a0ae2). However, you are right and the new implementation does not affect `lightdock` because it does not use the `Scheduler`. I will expand this implementation to third party libraries as well.

**Comment by joaomcteixeira** [comment]
Hi @amjjbonvin the last commit should address your question. I rose the catcher to `Step` so now it catches `KeyboardInterrupt` on both native and third-party libraries, for example:

Note the `^C` printed character.

#### in RIGIDBODY

```
[2021-11-03 12:38:58,349] haddock.libs.libparallel:L64 INFO - Scheduler configurated for 2 cpu cores.
[2021-11-03 12:38:58,349] haddock.libs.libparallel:L17 INFO - Worker ready with 1 tasks
[2021-11-03 12:38:58,349] haddock.libs.libparallel:L17 INFO - Worker ready with 1 tasks
[2021-11-03 12:38:58,349] haddock.libs.libparallel:L55 INFO - 2 tasks ready.
^C[2021-11-03 12:38:58,944] haddock.libs.libparallel:L88 INFO - The workers terminated in a controlled way
[2021-11-03 12:38:58,945] haddock.libs.libworkflow:L87 INFO - You have halted subprocess execution by hitting Ctrl+c
[2021-11-03 12:38:58,945] haddock.libs.libworkflow:L88 INFO - Exiting...
```

#### in LightDock

```
^CProcess Tentacle-1:
[lightdock] INFO: Caught interrupt...
Process Tentacle-2:
Process Tentacle-3:
[kraken] WARNING: Kraken sunk to the bottom of the ocean
[lightdock] INFO: bye.
[2021-11-03 12:52:45,847] haddock.libs.libworkflow:L87 INFO - You have halted subprocess execution by hitting Ctrl+c
[2021-11-03 12:52:45,847] haddock.libs.libworkflow:L88 INFO - Exiting...
```
```

**Comment by rvhonorato** [comment]
Does this mean that every method needs to have a way to catch `ctrl-c`?

**Comment by joaomcteixeira** [comment]
No, the `ctrl-c` catch is defined in the `Step` and in the `Worker`.

**Comment by joaomcteixeira** [comment]
Conflicts solved, you can review.

**Review by rvhonorato — APPROVED** [review]
Code looks good!

**Pull request merged**
