### PR TITLE
Added support for 3-hydroxyproline (HY3)

### PR DESCRIPTION
**Pull request by amjjbonvin**
You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and you comply with the following criteria:

- [ ] You have stick to Python. Talk with us before adding other programming languages to HADDOCK3
- [x] Your PR is about CNS
- [ ] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [ ] You structured the code into small functions as much as possible. You can use classes if there's a (state) purpose
- [x] code follows our coding style
- [x] You wrote tests for the new code
- [x] `tox` tests pass. *Run `tox` command inside the repository folder*
- [x] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [x] PR does not add any *install dependencies* unless permission granted by the HADDOCK team
- [x] PR does not break licensing
- [ ] Your PR is about writing documentation for already existing code :fire:
- [ ] Your PR is about writing tests for already existing code :godmode:

---

This add supports for a new modified amino acid, 3-hydroxyproline (HY3).  Topology and parameters were added to the standard `protein-allhdg` files and the relevant CNS scripts were updated.

### CODE REVIEW

**Comment by amjjbonvin** [comment]
Solved issue #532

**Comment by amjjbonvin** [comment]
To test the new residue, I added a tripeptide containing HY3 to the `scoring` example. This is a single molecule and in that case the scoring returns the full energy of the system.  The new PDB file in the `data` dir only contains the backbone for HY3 and `haddock3` properly builds the missing atoms.

**Comment by amjjbonvin** [comment]
As a note we should create in the documentation a list of supported modified amino acids and other molecules like glycans as is currently reported at https://wenmr.science.uu.nl/haddock2.4/library

**Review by joaomcteixeira — APPROVED** [review]
I am happy this addition went through so smoothly.
The documentation has that information, but it is very technical and is extracted automatically from the `supported_molecules.py` file. Surely, we should work out a more user-friendly way. I will try to address it.

**Review by rvhonorato — APPROVED** [review]
This adds `HY3` support to `emref`,`flexref`,`mdref`,`rigidbody`,`emscoring`,`mdscoring` and `topoaa`.

Addition touches only CNS scripts - looks good to me

**Pull request merged**
