### PR TITLE
Add option to sort-by in `caprieval`

### LINKED ISSUE #153: Add option to "sortby" in `caprieval`
We could sort the output of `caprieval` by `score` or some of the calculated metrics.

### PR DESCRIPTION
**Pull request by rvhonorato**
This is a remake of #182, now [in pure-python implementation since we should not use `pandas`](https://github.com/haddocking/haddock3/pull/182#issuecomment-987864556) which again closes #153.

### CODE REVIEW

**Review by amjjbonvin — APPROVED** [review]
Shouldn't the `default.cfg` file of the module reflect the sorting option? There must be a parameter for it.

**Comment by joaomcteixeira** [comment]
I am reviewing the PR still

**Comment by rvhonorato** [comment]
> Shouldn't the `default.cfg` file of the module reflect the sorting option? There must be a parameter for it.

I've added these two parameters, is that what you mean?
```python
sortby = 'score'
ascending = true
```

**Comment by amjjbonvin** [comment]
Yes - all fine - I though I had deleted this comment :-)

**Comment by joaomcteixeira** [comment]
Cool sort implementation Rodrigo. I know it is an extra effort but very easily we removed the need for `pandas`. I gave it a stylish touch to the table:

```
             model                  score     irmsd      fnat     lrmsd    ilrmsd
01_rigidbody/rigidbody_9.pdb      -29.179     6.988     0.110    16.523     6.787
01_rigidbody/rigidbody_11.pdb     -28.741     6.962     0.110    16.497     6.776
01_rigidbody/rigidbody_3.pdb       21.658    20.290     0.027    48.668    19.170
01_rigidbody/rigidbody_6.pdb      -26.634     7.404     0.027    13.514     6.896
01_rigidbody/rigidbody_1.pdb      -39.067     7.695     0.014    13.067     7.245
01_rigidbody/rigidbody_4.pdb      -31.412    22.005     0.014    26.558    33.819
01_rigidbody/rigidbody_10.pdb     -31.320    21.934     0.014    26.513    32.703
01_rigidbody/rigidbody_13.pdb     -27.623    21.909     0.014    26.058    30.797
```

Now it is also human-readable. Separators are spaces.

If you don't have anything more to add, it is good to merge. Go for it,

**Pull request merged**
