### PR TITLE
Zip structures

### LINKED ISSUE #791: zip top clusters/structures for downloading purposes
when running the analysis of the last step of the workflow it would be nice to compress the files that are shown in the report, so that the end user can download all of them with only one click.

### PR DESCRIPTION
**Pull request by mgiulini**
You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and that you comply with the following criteria:

- [ ] You have sticked to Python. Please talk to us before adding other programming languages to HADDOCK3
- [ ] Your PR is about CNS
- [ ] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [ ] You structured the code into small functions as much as possible. You can use classes if there is a (state) purpose
- [ ] Your code follows our coding style
- [ ] You wrote tests for the new code
- [ ] `tox` tests pass. *Run `tox` command inside the repository folder*
- [ ] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [ ] PR does not add any dependencies, unless permission granted by the HADDOCK team
- [ ] PR does not break licensing
- [ ] Your PR is about writing documentation for already existing code :fire:
- [ ] Your PR is about writing tests for already existing code :godmode:

---

Closes #791 by adding a function that, at the analysis/postprocessing stage, zips the top 4 structures of the best ranked 10 clusters in case clustering information is available. Otherwise, the top ranked 10 models are zipped.

Further details:

- it handles gzipped pdb structures
- structures are renamed according to the `cluster_${cluster_rank}\_model_${model_rank}.pdb` logic
- the zipped file is called summary.tgz (similarly to the 2.4 server)
- if some or all the structures are not available the execution is not stopped but several warning messages are raised

### CODE REVIEW

**Review by amjjbonvin — APPROVED** [review]
Looks good to me - I leave the Python implementation details to others :-)

**Review by VGPReys — COMMENTED** [review]
- [X] Should be working
- [ ] Maybe missing `tests` functions.
- [ ] Hard-coded `4` and `10` (as is haddock2.4), but someone may want to modify these values for their own usage?
- [ ] Not propagated to any download links in the analysis

**Comment by mgiulini** [comment]
> * [x]  Should be working
> * [ ]  Maybe missing `tests` functions.
complicated to test this function as zipping multiple files is involved..I'll see what I can do
> * [ ]  Hard-coded `4` and `10` (as is haddock2.4), but someone may want to modify these values for their own usage?
I would not do that now, as it probably won't be necessary
> * [ ]  Not propagated to any download links in the analysis
I thought to address that in another PR

**Comment by mgiulini** [comment]
@VGPReys added the test! as for the download button, I think that should be addressed within the webapp

**Review by VGPReys — COMMENTED** [review]
Ready to go 🚀  !

**Comment by sverhoeven** [comment]
Thanks for the archive, I have added download links to webapp at https://github.com/i-VRESSE/haddock3-webapp/pull/75

**Pull request merged**
