### PR TITLE
Add third-party module `gdock`

### PR DESCRIPTION
**Pull request by rvhonorato**
This PR adds the unrequested third-party module [`gdock`](https://github.com/rvhonorato/gdock) that demonstrates the easiness of integration with the current haddock3 workflow;

`topology > gdock > cluster-fcc > select-top-cluster > flexible-refinement > md-refinement`

[`gdock`](https://github.com/rvhonorato/gdock) has an option to do a  "dry run" in which it just generates models and nothing else. By passing this option to the module we can generate a bunch of models with the genetic algorithm sampling routine and then pass them to the flexible-refinement and md-refinement. 🐙 

* * *

```
##############################################
#                                            #
#                 HADDOCK 3                  #
#                                            #
##############################################

Starting HADDOCK 3.0.beta-unreleased on 2021-08-13 10:14:00

Python 3.9.5 (default, May 18 2021, 12:31:01) 
[Clang 10.0.0 ]

[2021-08-13 10:14:59,771] haddock.libs.libutil:L53 WARNING - /Users/rodrigo/repos/haddock3/examples/thirdparty/gdock/run1 exists and it will be REMOVED!
[2021-08-13 10:14:59,812] haddock.workflow:L34 INFO - Reading instructions of [topoaa] step
[2021-08-13 10:14:59,812] haddock.workflow:L34 INFO - Reading instructions of [gdock] step
[2021-08-13 10:14:59,812] haddock.workflow:L34 INFO - Reading instructions of [clustfcc] step
[2021-08-13 10:14:59,812] haddock.workflow:L34 INFO - Reading instructions of [seletopclusts] step
[2021-08-13 10:14:59,812] haddock.workflow:L34 INFO - Reading instructions of [flexref] step
[2021-08-13 10:14:59,813] haddock.workflow:L34 INFO - Reading instructions of [mdref] step
[2021-08-13 10:14:59,860] haddock.modules.topology.topoaa:L56 INFO - Running [allatom] module
[2021-08-13 10:14:59,860] haddock.modules.topology.topoaa:L57 INFO - Generating topologies
[2021-08-13 10:14:59,861] haddock.modules.topology.topoaa:L66 INFO - 1 - /Users/rodrigo/repos/haddock3/examples/thirdparty/gdock/1a2k_l_u.pdb
[2021-08-13 10:14:59,861] haddock.modules.topology.topoaa:L73 INFO - Split models if needed for /Users/rodrigo/repos/haddock3/examples/thirdparty/gdock/run1/00_topoaa/1a2k_l_u.pdb
[2021-08-13 10:14:59,868] haddock.modules.topology.topoaa:L79 INFO - Sanitizing molecule 1a2k_l_u.pdb
[2021-08-13 10:14:59,922] haddock.modules.topology.topoaa:L88 INFO - Topology CNS input created in /Users/rodrigo/repos/haddock3/examples/thirdparty/gdock/run1/00_topoaa/1a2k_l_u.inp
[2021-08-13 10:14:59,926] haddock.modules.topology.topoaa:L66 INFO - 2 - /Users/rodrigo/repos/haddock3/examples/thirdparty/gdock/1a2k_r_u.pdb
[2021-08-13 10:14:59,927] haddock.modules.topology.topoaa:L73 INFO - Split models if needed for /Users/rodrigo/repos/haddock3/examples/thirdparty/gdock/run1/00_topoaa/1a2k_r_u.pdb
[2021-08-13 10:14:59,933] haddock.modules.topology.topoaa:L79 INFO - Sanitizing molecule 1a2k_r_u.pdb
[2021-08-13 10:15:00,016] haddock.modules.topology.topoaa:L88 INFO - Topology CNS input created in /Users/rodrigo/repos/haddock3/examples/thirdparty/gdock/run1/00_topoaa/1a2k_r_u.inp
[2021-08-13 10:15:00,018] haddock.modules.topology.topoaa:L104 INFO - Running CNS engine with 2 jobs
[2021-08-13 10:15:00,019] haddock.parallel:L46 INFO - Running with 2 cpu cores
[2021-08-13 10:15:00,020] haddock.parallel:L14 INFO - Worker ready with 1 tasks
[2021-08-13 10:15:00,020] haddock.parallel:L14 INFO - Worker ready with 1 tasks
[2021-08-13 10:15:00,021] haddock.parallel:L57 INFO - 2 tasks ready
[2021-08-13 10:15:06,616] haddock.parallel:L68 INFO - 2 tasks finished
[2021-08-13 10:15:06,618] haddock.modules.topology.topoaa:L107 INFO - CNS engine has finished
[2021-08-13 10:15:06,647] haddock.modules.sampling.gdock:L43 INFO - Running [gdock] module
[2021-08-13 10:15:09,651] haddock.modules.sampling.gdock:L73 INFO - No chain IDs found, using segid information
[2021-08-13 10:15:09,668] haddock.modules.sampling.gdock:L73 INFO - No chain IDs found, using segid information
==================================================================
#                      Welcome to gdock!                          
#
# "The world will not be inherited by the strongest, it will be inherited by those most able to change"
#   -Charles Darwin
#
==================================================================
 2021-08-13 10:15:10,551 gdock:41 INFO - Starting at Fri Aug 13 10:15:10 2021
 2021-08-13 10:15:10,552 gdock:42 INFO - Running v1.1.0
 2021-08-13 10:15:10,552 gdock:44 INFO - Setting up simulation
 2021-08-13 10:15:10,556 setup:39 INFO - Initializing
 2021-08-13 10:15:10,556 setup:41 INFO - Checking for dependencies
 2021-08-13 10:15:10,679 setup:68 INFO - Copying input molecules to run folder
 2021-08-13 10:15:10,683 gdock:51 INFO - Loading Structures module
 2021-08-13 10:15:10,759 gdock:57 INFO - Loading Restraints module
 2021-08-13 10:15:10,776 gdock:63 INFO - Loading Geometry module
 2021-08-13 10:15:10,776 geometry:28 INFO - Positioning molecules in starting conformation
 2021-08-13 10:15:10,815 geometry:97 INFO - Applying transformations for initial position
 2021-08-13 10:15:11,043 gdock:69 INFO - Loading Genetic Algorithm module
 2021-08-13 10:15:11,058 ga:99 INFO - Running the Genetic Algorithm!
 2021-08-13 10:15:11,282 ga:105 INFO - Your random seed is: 42
 2021-08-13 10:15:11,282 ga:110 INFO - Population: 25 Max Generations: 5
 2021-08-13 10:15:11,282 ga:112 INFO - Gen ... mean +- sd (min, max)
 2021-08-13 10:15:13,457 ga:189 INFO - Gen 001 0.26 +- 0.11 (0.06, 0.50) eval=25
 2021-08-13 10:15:14,259 ga:189 INFO - Gen 002 0.38 +- 0.10 (0.22, 0.50) eval=21
 2021-08-13 10:15:14,955 ga:189 INFO - Gen 003 0.47 +- 0.07 (0.22, 0.56) eval=22
 2021-08-13 10:15:15,793 ga:189 INFO - Gen 004 0.50 +- 0.03 (0.39, 0.56) eval=23
 2021-08-13 10:15:16,482 ga:189 INFO - Gen 005 0.51 +- 0.04 (0.39, 0.56) eval=21
 2021-08-13 10:15:16,482 ga:196 INFO - Simulation reached maximum number of generations, stopping at 5.
 2021-08-13 10:15:16,555 ga:288 INFO - Dumping structures for this epoch
 2021-08-13 10:15:18,256 gdock:75 INFO - This is a dry run, stopping after models are generated
[2021-08-13 10:15:18,382] haddock.modules.analysis.clustfcc:L23 INFO - Running [clustfcc] module
[2021-08-13 10:15:18,382] haddock.modules.analysis.clustfcc:L34 INFO - Calculating contacts
[2021-08-13 10:15:18,386] haddock.parallel:L46 INFO - Running with 4 cpu cores
[2021-08-13 10:15:18,387] haddock.parallel:L14 INFO - Worker ready with 14 tasks
[2021-08-13 10:15:18,387] haddock.parallel:L14 INFO - Worker ready with 14 tasks
[2021-08-13 10:15:18,387] haddock.parallel:L14 INFO - Worker ready with 13 tasks
[2021-08-13 10:15:18,387] haddock.parallel:L14 INFO - Worker ready with 13 tasks
[2021-08-13 10:15:18,387] haddock.parallel:L57 INFO - 54 tasks ready
[2021-08-13 10:15:21,493] haddock.parallel:L68 INFO - 54 tasks finished
[2021-08-13 10:15:21,495] haddock.modules.analysis.clustfcc:L62 INFO - Calculating the FCC matrix
[2021-08-13 10:15:21,566] haddock.modules.analysis.clustfcc:L79 INFO - Clustering...
[2021-08-13 10:15:21,638] haddock.modules.analysis.seletopclusts:L19 INFO - Running [seletopclusts] module
[2021-08-13 10:15:21,893] haddock.modules.refinement.flexref:L64 INFO - Running [flexref] module
[2021-08-13 10:15:21,910] haddock.modules.refinement.flexref:L97 INFO - Running CNS engine with 4 jobs
[2021-08-13 10:15:21,911] haddock.parallel:L46 INFO - Running with 4 cpu cores
[2021-08-13 10:15:21,912] haddock.parallel:L14 INFO - Worker ready with 1 tasks
[2021-08-13 10:15:21,912] haddock.parallel:L14 INFO - Worker ready with 1 tasks
[2021-08-13 10:15:21,912] haddock.parallel:L14 INFO - Worker ready with 1 tasks
[2021-08-13 10:15:21,912] haddock.parallel:L14 INFO - Worker ready with 1 tasks
[2021-08-13 10:15:21,912] haddock.parallel:L57 INFO - 4 tasks ready
[2021-08-13 10:18:00,942] haddock.parallel:L68 INFO - 4 tasks finished
[2021-08-13 10:18:00,943] haddock.modules.refinement.flexref:L100 INFO - CNS engine has finished
[2021-08-13 10:18:01,109] haddock.modules.refinement.mdref:L62 INFO - Running [mdref] module
[2021-08-13 10:18:01,124] haddock.modules.refinement.mdref:L95 INFO - Running CNS engine with 4 jobs
[2021-08-13 10:18:01,125] haddock.parallel:L46 INFO - Running with 4 cpu cores
[2021-08-13 10:18:01,125] haddock.parallel:L14 INFO - Worker ready with 1 tasks
[2021-08-13 10:18:01,126] haddock.parallel:L14 INFO - Worker ready with 1 tasks
[2021-08-13 10:18:01,126] haddock.parallel:L14 INFO - Worker ready with 1 tasks
[2021-08-13 10:18:01,126] haddock.parallel:L14 INFO - Worker ready with 1 tasks
[2021-08-13 10:18:01,126] haddock.parallel:L57 INFO - 4 tasks ready
[2021-08-13 10:22:33,396] haddock.parallel:L68 INFO - 4 tasks finished
[2021-08-13 10:22:33,397] haddock.modules.refinement.mdref:L98 INFO - CNS engine has finished
[2021-08-13 10:22:33,419] root:L68 INFO - Finished at 13/08/2021 10:22:33. Tot ziens! Good bye! Adéu-siau!
```

### CODE REVIEW

**Comment by rvhonorato** [comment]
Also: the number of individuals and generations here in the example are just illustrative, the default is 5.000 individuals over either 50 generations or convergence.

**Review by joaomcteixeira — CHANGES_REQUESTED** [review]
Looks a very straight forward integration. What I think is missing or needs to be changed:

* add instructions on how to install `gdock`. In the lines of #29 , we can have a extra file `install-thirdparty.md` with the instruction on how to install the thirdparty optional software that haddock3 integrates. Later we can add instructions for lightdock as well and address that issue.
* PBDs `1a2k_1_u.pdb` are already in `examples/docking`, that is too much PDB repeating. I suggest moving those PDBs to a parent folder, for example, `examples/data` or `examples/structures` and make all the examples feed from those PDBs. Like this we avoid having repeated PDB files.

:rocket:

**Comment by rvhonorato** [comment]
>    add instructions on how to install `gdock`. In the lines of [Change LightDock to an optional dependency #29](https://github.com/haddocking/haddock3/issues/29) , we can have a extra file `install-thirdparty.md` with the instruction on how to install the thirdparty optional software that haddock3 integrates. Later we can add instructions for lightdock as well and address that issue.

Added

>    PBDs `1a2k_1_u.pdb` are already in `examples/docking`, that is too much PDB repeating. I suggest moving those PDBs to a parent folder, for example, `examples/data` or `examples/structures` and make all the examples feed from those PDBs. Like this we avoid having repeated PDB files.

Done with https://github.com/haddocking/haddock3/pull/73

**Review by joaomcteixeira — APPROVED** [review]
:+1:

**Pull request merged**
