### PR TITLE
Glycan example

### LINKED ISSUE #710: create a protein-glycan docking example
another example cfg file to go in the examples folder, showing how to use HADDOCK3 to create accurate predictions of protein-glycan complexes

### PR DESCRIPTION
**Pull request by mgiulini**
You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and that you comply with the following criteria:

- [x] You have sticked to Python. Please talk to us before adding other programming languages to HADDOCK3
- [ ] Your PR is about CNS
- [ ] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [ ] You structured the code into small functions as much as possible. You can use classes if there is a (state) purpose
- [x] Your code follows our coding style
- [ ] You wrote tests for the new code
- [x] `tox` tests pass. *Run `tox` command inside the repository folder*
- [ ] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [x] PR does not add any dependencies, unless permission granted by the HADDOCK team
- [ ] PR does not break licensing
- [ ] Your PR is about writing documentation for already existing code :fire:
- [ ] Your PR is about writing tests for already existing code :godmode:

---

Closes #710 by creating a new subdirectory within the examples folder, namely `docking-protein-glycan`, with the new haddock3 workflow to dock proteins to unbound glycans. The classic test.cfg and full.cfg files are included.

Data comes from Anna Ranaudo's work on glycans (to be published soon): a reference to that will be added when available.

As soon as PR #685 will be merged, another workflow can be created, with ilrmsdmatrix in place of the rmsdmatrix steps.

### CODE REVIEW

**Review by rvhonorato — DISMISSED** [review]
In my opinion this (and the other) examples should not be here since they are not needed to run the application and this is a code repository.

Why not add this to https://github.com/haddocking/haddock-examples?

**Comment by mgiulini** [comment]
That is possible, but it would be a major change in the repository (and quite unrelated to this PR). In my opinion such a migration should be discussed and, if/when approved, implemented independently on this PR.

**Comment by rvhonorato** [comment]
I'd suggest then you close this and move it - but need to see what is Rule 1 on this, what you say @amjjbonvin ?

**Comment by mgiulini** [comment]
I would instead merge this and, if necessary, move everything later. As for now, we heavily rely on the examples during the development. Not saying that your solution does not make sense (it does), just that it would be a major change for haddock3. let's see what @amjjbonvin thinks.

**Comment by amjjbonvin** [comment]
We have currently all examples in the examples directory - these serve as integration tests. But we could indeed move those to a separate repo (e.g. `haddock3-examples`) and make it a sub-dependency of the installation.  It is important for users to have access to those examples. And at this time I am running those to make sure we get similar results as before (after changes).

**Review by amjjbonvin — APPROVED** [review]

**Review by VGPReys — APPROVED** [review]

**Review by VGPReys — APPROVED** [review]

**Pull request merged**
