### PR TITLE
Updates install instructions after dropping python 3.8 and adopting FCC2

### PR DESCRIPTION
**Pull request by joaomcteixeira**
Updates install instructions after dropping python 3.8 and adopting FCC2 - #130

### CODE REVIEW

**Review by amjjbonvin — APPROVED** [review]

**Comment by amjjbonvin** [comment]
But some tests are failing...

**Comment by joaomcteixeira** [comment]
ohhh CI, CI. what is still creating `src/fcc`? give me some minutes

**Review by rvhonorato — CHANGES_REQUESTED** [review]
`clustfcc` needs to be refactored to use fccpy before we can update the instructions.

**Comment by joaomcteixeira** [comment]
I apologise... I went to rushy in this PR. Also, @rvhonorato is right about #133 . Lets do that first.

**Pull request closed without merging**
