### PR TITLE
Make `caprieval` automatically match numbering and identify atoms

### PR DESCRIPTION
**Pull request by rvhonorato**
This PR fixes a silent bug with the definition of which zones should be used for calculating the capri metrics. Basically it would work every time a given number had the same backbone atoms as the reference, but if the model had atoms not present in the reference, it would fail with a cryptic error.

This happened due to the lack of proper numbering/atom match between reference and model. This PR fixes this by addressing:
1. How atoms are defined
2. How numbering match is defined

* * *
## 1. How atoms are defined

Protein backbone atoms and DNA base atoms are used but we need to also account for other molecule types such as ligands, glycans, modified aminoacids etc.

```python
PROT_ATOMS = ["C", "N", "CA", "O"]
# Bases
DNA_ATOMS = [
    "C5",
    "N9",
    "N2",
    "C8",
    "O2",
    "N4",
    "N7",
    "C7",
    "N1",
    "N6",
    "C2",
    "O4",
    "C6",
    "N3",
    "C4",
    "O6"]
```

When modified aminoacids or ligands are found, *all atoms different from hydrogen* are selected but they are restricted to a specific `RESIDUE_NAME` so that we do not contaminate the atom definitions.

For example when reading residue `NEP`: `CB`, `CG`, etc would be added to the atom pool, thus the selection would no longer contain only backbone atoms. But since these atoms are restricted to this specific `RESIDUE_NAME` we preserve the atomic definitions.

```
ATOM    620  N   NEP A  90      -2.292  -0.936  -2.702  1.00 15.00      A    N  
ATOM    621  HN  NEP A  90      -1.842  -1.595  -2.133  1.00 15.00      A    H  
ATOM    622  CA  NEP A  90      -3.559  -1.298  -3.353  1.00 15.00      A    C  
ATOM    623  CB  NEP A  90      -3.298  -2.187  -4.554  1.00 15.00      A    C  
ATOM    624  CG  NEP A  90      -4.559  -2.594  -5.267  1.00 15.00      A    C  
...
```

Same goes for ligands, we will look for this atoms only within its own `RESIDUE_NAME`
```
ATOM   5885  C82 G39 B 500       2.819  -3.696 -13.410  1.00 15.00      B    C  
ATOM   5886  C81 G39 B 500       2.614  -2.210 -13.614  1.00 15.00      B    C  
ATOM   5887  C8  G39 B 500       2.781  -1.396 -12.332  1.00 15.00      B    C  
ATOM   5888  C9  G39 B 500       2.232   0.019 -12.571  1.00 15.00      B    C  
ATOM   5889  C91 G39 B 500       2.962   0.769 -13.674  1.00 15.00      B    C  
ATOM   5890  O7  G39 B 500       4.163  -1.386 -11.915  1.00 15.00      B    O  
ATOM   5891  C6  G39 B 500       4.385  -0.903 -10.572  1.00 15.00      B    C  
ATOM   5892  C7  G39 B 500       5.183   0.391 -10.617  1.00 15.00      B    C  
ATOM   5893  C2  G39 B 500       5.938   0.843  -9.591  1.00 15.00      B    C  
ATOM   5894  C1  G39 B 500       6.242   2.280  -9.477  1.00 15.00      B    C  
ATOM   5895  O1B G39 B 500       7.018   2.679  -8.575  1.00 15.00      B    O  
ATOM   5896  O1A G39 B 500       5.728   3.091 -10.288  1.00 15.00      B    O  
ATOM   5897  C3  G39 B 500       6.487  -0.125  -8.565  1.00 15.00      B    C  
ATOM   5898  C4  G39 B 500       5.591  -1.357  -8.396  1.00 15.00      B    C  
ATOM   5899  N4  G39 B 500       6.319  -2.354  -7.628  1.00 15.00      B    N  
ATOM   5903  C5  G39 B 500       5.140  -1.940  -9.741  1.00 15.00      B    C  
ATOM   5904  N5  G39 B 500       4.304  -3.113  -9.549  1.00 15.00      B    N  
ATOM   5906  C10 G39 B 500       4.676  -4.349  -9.904  1.00 15.00      B    C  
ATOM   5907  C11 G39 B 500       3.817  -5.457  -9.370  1.00 15.00      B    C  
ATOM   5908  O10 G39 B 500       5.647  -4.586 -10.611  1.00 15.00      B    O 
```

These atoms definitions are **for now** hard-coded, we might change it later.
* * *
## 2. How numbering match is defined

When comparing the reference with the model, more often then not these are different structures since likely the reference is the bound structure and the model comes from the unbound form; each obtained in a different. 

For this reason usually one of them has either different numbering, gaps, missing side-chains and other differences. With this PR I implemented two ways of mapping the model to a given reference:

* Sequence Alignment with `biopython` via `Bio.Align`
* Structural Alignment with [LovoAlign](https://github.com/m3g/lovoalign)

This is a now a parameter called `aligned_method` with can be `sequence`/`structure`

Both methods work similarly by aligning the chains and using the alignment as a guide to relate which residue in the reference relates to which residue in the model. 

One limitation is that neither methods can perform small-molecule alignment, when a ligand is identified we do sequential matching, meaning `reference ligand residue id1 == model ligand residue id1`, despite the numbering (one can be 500 and the other 42).

Both will write the alignment files to `xx_caprieval` which can be used to check things and also print the identities:

```text
(...)
[2021-12-27 13:56:01,953 capri INFO] Sequence identity of chain A is 54.88%
(...)

# blosum62_N.aln
V--KLAGN-SSL---CP-IN-GWAV-YSKDNSIRI--GSKGDVFVI-REPFISCSHLE---CRTF-F-LT-QGA--LLND-KHSNG-TVK-DRS-PHRTL-MSCP-VGEA-PSYN--SRFESV--AWSASACHDGT-SWLT-IG-ISGPD--NGAV-A--VLKYNG-IITDTIK-SW-RNNILRTQESECA-CVNGSCFTV-MTDGPS-NGQA-SYKI-FKMEKGKVVK--SVE-LDAP-NY--HY-EECSCYPNA---GEIT-CVCRDNWH-GSNRPWVSF-NQ-NLE-YQ-IG---YICSG-VFGDN-PRPNDG--TGS---CG--PVSS--GAY--GVKGFSFKYG-NG--VWIGRT--KSTNS-RSGFE---MI--WD--PNGWTETDS-SFS-V-KQDIVAI-TDW--SGYSGS-F-VLT-GLD--CI-RPCFWVELIRGRPK-EST-IW-TSGSSIS--FCGVN-SD-TV-GW--SWPDGAE-L---PFTI
|--.---|-|-----|--|--|.|--.|||||||.--|--||..|--|||..||---.---|--.-|-|--||---|--|-||||--||--||--|||||-|.---.|---|-..--.|-.-|--|||.|.||||--.||--.--|.|-|--|-|--|--.--|.|-..-|.|--||-.|-|||||||||--|.||.|-||-||||-|-.|.|-.-.|-|-.|.||.|---|---|-|--.---|--|||||||-----|-.--|.|||||--|||||-|---.--|.|-|--|----|.|||-|-||--||-||---.-|---|---|-..--|----||||..|----||--.|.|||--|--.--|||.|---.|--|---||------|-|---.-.|-..-.-.|---|||||--|-|---|----||-|-||.|||||||-|-|-|-.|-||-.||---|||---|--|--|---||||||--.---|--|
VEYR---NWS--KPQC-QI-TGFA-PFSKDNSIRLSAG--GDIWV-TREPYVSC---DPVKC--YQFAL-GQG-TTL--DNKHSN-DTV-HDR-IPHRTLLMN--ELG--VP-FHLGTR-Q-VCIAWSSSSCHDG-KAWL-HV-CITG-DDKN-A-TASFI--YDGRLV-DSI-GSWSQN-ILRTQESEC-VCINGTC-TVVMTDG-SASGRADT-RILF-IEEGKIV-HIS--PL-A-GS-AQH-VEECSCYP--RYPG-V-RCICRDNW-KGSNRP-V--VD-INMEDY-SI-DSSYVCSGLV-GD-TPR-ND-DRS-SNSNC-RNP-NNERG--TQGVKGWAF---DNGNDLWMGRTISK--D-LRSGYETFKVIGGW-STPN------SKS--QINRQ-VI-VDSD-NRSGYSG-IFSV--EG--KSCINR-CFYVELIRGR-KQE-TRVWWTS-NSI-VVFCG--TS-GT-YG-TGSWPDGA-NINFMP--I

```

or

```text
(...)
[2021-12-27 13:51:07,861 capri INFO] "Structural" identity of chain A is 97.89%
(...)

# lovoalign_N.aln
         83 -VKLAGNSSLCPINGWAVYSKDNSIRIGSKGDVFVIREPFISCSHLECRT   131
         82 VEYRNWSKPQCQITGFAPFSKDNSIRLSAGGDIWVTREPYVSCDPVKCYQ   131
            .         .         .         .         .
        132 FFLTQGALLNDKHSNGTVKDRSPHRTLMSCPVGEAPSPYNSRFESVAWSA   180
        132 FALGQGTTLDNKHSNDTVHDRIPHRTLLMNELGVPFHLG-TRQVCIAWSS   180
            .         .         .         .         .
        181 SACHDGTSWLTIGISGPDNGAVAVLKYNGIITDTIKSWRNNILRTQESEC   230
        181 SSCHDGKAWLHVCITGDDKNATASFIYDGRLVDSIGSWSQNILRTQESEC   230
            .         .         .         .         .
        231 ACVNGSCFTVMTDGPSNGQASYKIFKMEKGKVVKSVELDAPNYHYEECSC   280
        231 VCINGTCTVVMTDGSASGRADTRILFIEEGKIVHISPLAGSAQHVEECSC   280
            .         .         .         .         .
        281 YPNAGEITCVCRDNWHGSNRPWVSFNQ-NLEYQIGYICSGVFGDNPRPND   330
        281 YPRYPGVRCICRDNWKGSNRPVVDINMEDYSIDSSYVCSGLVGDTPRNDD   330
            .         .         .         .         .
        331 G-TGS-C-GPVSSNGAYGVKGFSFKYGNGVWIGRTKSTNSRSGFEMIWDP   380
        331 RSSNSNCRNPNNERGTQGVKGWAFDNGNDLWMGRTISKDLRSGYETFKVI   380
            .         .         .         .         .
        381 NGWTE-TDSSFSVKQDIVAITDWSGYSGSFVQHPELTGLDCIRPCFWVEL   426
        381 GGWSTPNSKSQINRQVIVDSDNRSGYSGIFSVE---G-KSCINRCFYVEL   426
            .         .         .         .         .
        427 IRGRPKES-TIWTSGSSISFCGVNSDTVGWSWPDGAELP-FTI          468
        427 IRGRKQETRVWWTSNSIVVFCGTSGTYGTGSWPDGANINFMPI          469
```

From the alignment above you can see that the structural alignment does a much better job at mapping, and the sequence alignment will likely produce the wrong results. But since we must not add non-python dependencies to the project, ~I coded it so it is an optional dependency that must be installed on its own and made accessible via a  system variable `LOVOALIGN_EXEC`.~ the executable must be defined as `lovoalign_exec` parameter, example:

```
[caprieval]
reference = 'data/target.pdb'
alignment_method = "structure"
lovoalign_exec = "/Users/rodrigo/software/lovoalign-21.027/bin/lovoalign"
```

***
## Final consideration

Sorry for the two-features in the same PR 😉 

This automated definition of regions will follow the GIGO principle, if your reference is wildly different than the model and use the sub-optimal method, the mapping will be bad and the values will not be accurate. The safest way to ensure the metrics are accurate is to manually prepare the reference structure.

Still to be done since this PR already has too many changes:
* Make `caprieval` read ProFit input files #229 
* Chain matching #179 
    * if model is BA but reference is AB

### CODE REVIEW

**Review by joaomcteixeira — APPROVED** [review]
@rvhonorato I made the `lovoalign_exec` a configuration parameter instead of a global variable. It was running on my side. Check if it still behaves as you expect and if so, you can merge. :+1: nice job mate.

**Comment by rvhonorato** [comment]
Thanks @joaomcteixeira, just added one extra raise.

Its working as expected, just waiting for @amjjbonvin review before I merge it.

**Comment by joaomcteixeira** [comment]
Perfect @rvhonorato if @amjjbonvin aggress you can merge. Note that there will be LOTS of merge conflicts to merge this one and #219 . Please let me handle the merge conflicts regardless of whichever gets merged first.

**Review by amjjbonvin — APPROVED** [review]
Working fine indeed! Good job.

One comment though:

I am seeing for the protein-protein example:
```
[2021-12-29 15:06:28,949 capri INFO] Sequence identity of chain A is 99.33%
[2021-12-29 15:06:28,951 capri INFO] Sequence identity of chain B is 100.00%
```

But I assume it is rather a missing residue somewhere and not a different amino acid. These are different things...  Or is the difference due to the phospho-histidine?  HIS <-> HEP

**Comment by amjjbonvin** [comment]
Formally the same residues, but NEP with a post-translational modification.
Anyway - fine as is - very nice.

**Comment by rvhonorato** [comment]
> Formally the same residues, but NEP with a post-translational modification.

Oh yes, that's true but for our purposes here since the number of atoms are different between them if we make them equivalent there will be an error down the line.

But this is a good point @amjjbonvin, I changed so that both the reference and the model have `NEP`, for example, and they are not  matched properly:

```
...VELFVX-FGID...
...|||||--||||...
...VELFV-XFGID...
```

Meaning that as its now, the module will ignore non-standard aminoacids in the calculation and for mixed systems (protein-ligand + protein) it will ignore the ligand, this is quite a complex logic, I will open another issue about it and handle it there.

**Pull request merged**
