### PR TITLE
Update docking example to Classic HADDOCK docking

### PR DESCRIPTION
**Pull request by rvhonorato**
Updates the docking example to reflect the classic HADDOCK docking protocol. 

🚧 🚧 🚧 🚧

### CODE REVIEW

**Comment by amjjbonvin** [comment]
I suggest to have a `data` directory in each example and not as a common one. As we add more examples (like the ones for 2.4) the current structure would become messy with too many files in one location and possible conflicts.

**Comment by amjjbonvin** [comment]
And to really test things we should run the same examples as 2.4 (and not only BM5).

**Comment by rvhonorato** [comment]
> I suggest to have a `data` directory in each example and not as a common one. As we add more examples (like the ones for 2.4) the current structure would become messy with too many files in one location and possible conflicts.

Yes this is how it is in this pull request

**Comment by rvhonorato** [comment]
Surpassed by #145

**Pull request closed without merging**
