### PR TITLE
Deep CNS scripts checking and example cleaning

### PR DESCRIPTION
**Pull request by amjjbonvin**
You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and that you comply with the following criteria:

- [ ] You have sticked to Python. Please talk to us before adding other programming languages to HADDOCK3
- [X] Your PR is about CNS
- [ ] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [ ] You structured the code into small functions as much as possible. You can use classes if there is a (state) purpose
- [ ] Your code follows our coding style
- [ ] You wrote tests for the new code
- [x] `tox` tests pass. *Run `tox` command inside the repository folder*
- [X] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [X] PR does not add any dependencies, unless permission granted by the HADDOCK team
- [x] PR does not break licensing
- [ ] Your PR is about writing documentation for already existing code :fire:
- [ ] Your PR is about writing tests for already existing code :godmode:

---

A careful check of all output files of the various examples revealed several small issues like duplication of some parameters, missing variables in some CNS scripts, inconsistencies between files (format mainly) and example config files.

This pull request resolves all those issues.

### CODE REVIEW

**Comment by amjjbonvin** [comment]
@rvhonorato - tests are failing on my mac because of a difference in the 15th digit in the contacts module test... 
May-be an overkill?  I did not touch that module. They do pass here however.

```
========================================================================================== FAILURES ==========================================================================================
______________________________________________________________________________ test_make_ideogram_arc_moduloAB _______________________________________________________________________________

    def test_make_ideogram_arc_moduloAB():
        """Test usage of moduloAB while providing outranged angle values."""
        nb_points = 2
        arc_positions = make_ideogram_arc(1.1, (1, -1), nb_points=nb_points)
        excpected_output = np.array([
            0.5943325364549538 + 0.9256180832886862j,
            0.5943325364549535 - 0.9256180832886863j,
            ])
        assert arc_positions.shape == excpected_output.shape
        for i in range(nb_points):
>           assert arc_positions[i] == excpected_output[i]
E           assert (0.5943325364549534-0.9256180832886863j) == (0.5943325364549535-0.9256180832886863j)
```

As for the alascan integration test, if might need to be revisited...

**Comment by rvhonorato** [comment]
This test is wrong, looks like we missed it during #731. It's comparing two arrays down to its numeric precision - should be using `numpy.isclose`. 

[git blame](https://github.com/haddocking/haddock3/blame/e8a63d977f3f9b0b8fefd37937c3c472906a6b18/tests/test_module_contmap.py#L536 ) says @VGPReys added it, could you open another PR and change it?

**Comment by rvhonorato** [comment]
It's impossible for me to review 1.000+ lines, if you think its ok just go ahead and merge it!

**Comment by amjjbonvin** [comment]
It is possible :-)

A lot of those 1000 lines are simply files in which I corrected Windows style line ending into Linux.

All others have very similar changes.

**Pull request merged**
