### PR TITLE
Clean intermediate files in batch mode

### LINKED ISSUE #936: Cleaning does not remove all relevant files in batch mode
**Describe the bug**

When executing haddock3 in batch mode, the cleaning of files does not remove all the generated job files and the .err files returned by slurm.  All job files are still present, even when `clean=true`. 

**To Reproduce**

Run for example the docking-protein-protein example, and look into the 01_rigidbody directory. You will find files like:

```
rigidbody_156.err
rigidbody_156.job
```

**Expected behavior**

All .err and .job files should be deleted.

### PR DESCRIPTION
**Pull request by VGPReys**
You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and that you comply with the following criteria:

- [ ] You have sticked to Python. Please talk to us before adding other programming languages to HADDOCK3
- [ ] Your PR is about CNS
- [ ] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [ ] You structured the code into small functions as much as possible. You can use classes if there is a (state) purpose
- [ ] Your code follows our coding style
- [ ] You wrote tests for the new code
- [ ] `tox` tests pass. *Run `tox` command inside the repository folder*
- [ ] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [ ] PR does not add any dependencies, unless permission granted by the HADDOCK team
- [ ] PR does not break licensing
- [ ] Your PR is about writing documentation for already existing code :fire:
- [ ] Your PR is about writing tests for already existing code :godmode:

---

Close #936 

In batch mode, more files are created (e.g: `.job` and `.err`).
They were not part of the file extensions to be removed during the cleaning process.
This is now fixed !

### CODE REVIEW

**Comment by AnnaKravchenko** [comment]
Why is it `# deletes all except the first one` in line 62 in haddock3/src/haddock/gear/clean_steps.py?
I don’t understand why '.inp’ is in files_to_delete, since it is not to be deleted. From checking clean_steps.py I don’t see why ‘.inp’ should be in files_to_delete in general. 

Is there a reason for it, or can we remove it and change this `# deletes all except the first one` to just `# deletes all`?

**Comment by amjjbonvin** [comment]
We want to limit the number of files generated, but still keep the first one to be able to check things (e.g. that there is no issue in the generated CNS script)

There is now a general parameter called `less_io` that avoid writing to disk all those files.
Only works in local mode though (and MPI should work too in principle)

**Comment by AnnaKravchenko** [comment]
Ok, I understand that we want to keep '.inp' to be able to check that CNS runs fine, and that we still need this clean for batch mode.
 
But why then add `.inp` to `files_to_delete` to begin with? 
```
    # Files to delete
    # deletes all except the first one 
     files_to_delete = [
        '.inp',
        '.inp.gz',
        '.out',
        '.out.gz',
        '.job',
        '.err',
        ]

    for extension in files_to_delete:
        flist = glob_folder(path, extension)
        for file_ in flist[1:]:
            Path(file_).unlink()
```

Wouldn’t it be more logical to:
```
    # Files to delete
     files_to_delete = [
        '.inp.gz',
        '.out',
        '.out.gz',
        '.job',
        '.err',
        ]

    for extension in files_to_delete:
        flist = glob_folder(path, extension)
        for file_ in flist:
            Path(file_).unlink()
```
So it’s the same pattern for delete/archive/compress?

**Comment by amjjbonvin** [comment]
Because we only want to keep 1 and not 1 per model

**Comment by AnnaKravchenko** [comment]
Thank you, fully understrand:)

**Review by AnnaKravchenko — APPROVED** [review]
I see only [module]_1.job and [module]_1.err when running in haddock in batch mode, everything is as expected.  
For some reason, the outcome is the same with the main brunch. Maybe it has something to do with `less_io` Alex mentioned?

**Review by mgiulini — APPROVED** [review]

**Pull request merged**
