### PR TITLE
Unclustered structures

### LINKED ISSUE #480: Add a list of the non-clustered structures to `clustfcc`
Does it make sense to add the list of the non-clustered structures and their respective h-scores to the end of the `clustfcc.txt` file? I vote for that. Let me know.

### PR DESCRIPTION
**Pull request by mgiulini**
You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and you comply with the following criteria:

- [x] You have stick to Python. Talk with us before adding other programming languages to HADDOCK3
- [ ] Your PR is about CNS
- [x] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [x] You structured the code into small functions as much as possible. You can use classes if there's a (state) purpose
- [x] code follows our coding style
- [x] You wrote tests for the new code
- [x] `tox` tests pass. *Run `tox` command inside the repository folder*
- [x] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [x] PR does not add any *install dependencies* unless permission granted by the HADDOCK team
- [x] PR does not break licensing
- [ ] Your PR is about writing documentation for already existing code :fire:
- [ ] Your PR is about writing tests for already existing code :godmode:

---

Closes #480

### CODE REVIEW

**Comment by mgiulini** [comment]
Hi @amjjbonvin @joaomcteixeira, this PR addresses #480.
It simply compares the input models to the output models of the two clustering modules, saving the unclustered structures to the .txt file `unclustered.txt`.

- all the unclustered structures are saved. Is this ok?
- in the worst case scenario (10k input models) this has a light impact on the length of the workflow (about 8 seconds more on average)
- currently the file follows this format:
```
### Unclustered structures ###

1       emscoring_1017.pdb      -62.92
2       emscoring_1779.pdb      -61.38
...
2345       emscoring_1814.pdb      18.09
```
sorting the structures by the score. Should I specify the clustering parameters as well? (they are already included in the `clustfcc.txt` and `clustrmsd.txt` file)
-  if all the structures are in a cluster the file is still written to disk but left empty. Is this ok?

**Review by amjjbonvin — COMMENTED** [review]
Now you will have to look at two files to figure out the rank of a unclustered structure.

Why not write all models to that new file adding a column corresponding to the cluster number (or None if unclustered)?

**Comment by mgiulini** [comment]
> Now you will have to look at two files to figure out the rank of a unclustered structure.
> 
> Why not write all models to that new file adding a column corresponding to the cluster number (or None if unclustered)?

It makes more sense indeed, thanks for the suggestion!

**Comment by joaomcteixeira** [comment]
When implementing what @amjjbonvin suggested, and because the output file is tab-separated, I suggest choosing a character to annotate the unclustered structures to avoid having two consecutive tabs in case the cell is empty. Many times, programs or routines reading tab-separated files fail to distinguish two consecutive tags. You can use a `-` for example. Therefore;

```csv
1       emscoring_1017.pdb      -62.92      -
2       emscoring_1779.pdb      -61.38      -
3       emscoring_0000.pdb      -60.00      1
```

Is better than:

```csv
1       emscoring_1017.pdb      -62.92      
2       emscoring_1779.pdb      -61.38      
3       emscoring_0000.pdb      -60.00      1
```

IMHO,

**Comment by amjjbonvin** [comment]
Indeed!

**Comment by mgiulini** [comment]
I implemented the requested modifications, thank you for the useful suggestions!

**Review by joaomcteixeira — APPROVED** [review]
Code looks good :+1:
(I have not run the tests)
Cheers

**Pull request merged**
