### PR TITLE
ordered traceback

### LINKED ISSUE #830: order traceback table
the traceback table should be ordered according to the rank models take in the last step of the workflow

### PR DESCRIPTION
**Pull request by mgiulini**
You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and that you comply with the following criteria:

- [ ] You have sticked to Python. Please talk to us before adding other programming languages to HADDOCK3
- [ ] Your PR is about CNS
- [ ] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [ ] You structured the code into small functions as much as possible. You can use classes if there is a (state) purpose
- [ ] Your code follows our coding style
- [ ] You wrote tests for the new code
- [ ] `tox` tests pass. *Run `tox` command inside the repository folder*
- [ ] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [ ] PR does not add any dependencies, unless permission granted by the HADDOCK team
- [ ] PR does not break licensing
- [ ] Your PR is about writing documentation for already existing code :fire:
- [ ] Your PR is about writing tests for already existing code :godmode:

---

Closes #830 by ordering the traceback table according to the last column

### CODE REVIEW

**Review by VGPReys — APPROVED** [review]
This is sorting based on last column, which makes sense.
But could it be also sorted based on previous columns for initial models that did not make it until the end of the workflow ?
e.g:
[rigibody]
sampling = 1000
[seletop]
select = 200
[flexref]

in the example, the traceback would sort based on flexref, but randomize order for rigidbody models 201 to 1000.

**Comment by mgiulini** [comment]
> This is sorting based on last column, which makes sense. But could it be also sorted based on previous columns for initial models that did not make it until the end of the workflow ? e.g: [rigibody] sampling = 1000 [seletop] select = 200 [flexref]
> 
> in the example, the traceback would sort based on flexref, but randomize order for rigidbody models 201 to 1000.

fair point, it should be quite easy!

**Comment by mgiulini** [comment]
@VGPReys done! it should be fixed now

**Review by VGPReys — APPROVED** [review]

**Comment by VGPReys** [comment]
> @VGPReys done! it should be fixed now

Nice amazing !

**Pull request merged**
