### PR TITLE
Solves issue #1119 related to MPI execution with mpirun or run

### PR DESCRIPTION
**Pull request by amjjbonvin**
You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md).

## Checklist

- [ ] Tests added for the new code
- [ ] Documentation added for the code changes
- [X] Does not break licensing
- [x] Does not add any dependencies, if it does please add a thorough explanation

It does add `setuptools` as dependency. Present by default in Python3.9 but not 3.12

## Summary of the Pull Request  

This pull request modifies the `lipmpi.py` to check for the presence of `mpirun` and if not found for `srun` instead (as used on the Lumi HPC system). 

## Related Issue

Issue #1119

### CODE REVIEW

**Comment by mgiulini** [comment]
I did some googling and it seems that setuptools and distutils are marked as deprecated and will be removed from future python version: the better alternative here seems to replace 
`from distutils.spawn import find_executable
`
with
`from shutil import which`
and then using 
`if which("mpirun") is not None:
`
rather than
`if find_executable("mpirun") is not None:`

**Comment by amjjbonvin** [comment]
Thanks Marco - will implement and test

**Comment by amjjbonvin** [comment]
Tested on Lumi, using `shutil` and `which` - works fine. All tests passing.

**Review by mgiulini — APPROVED** [review]

**Review by VGPReys — DISMISSED** [review]
I modified the termination process, to finalize the haddock3 run properly.

**Review by mgiulini — APPROVED** [review]

**Pull request merged**
