### PR TITLE
Googleform

### PR DESCRIPTION
**Pull request by joaomcteixeira**
Adds a section for users to sign the google forms supporting HADDOCK3. Since the form is on the group's page, I thought it could be useful having it here as well. What do you think?

### CODE REVIEW

**Comment by rvhonorato** [comment]
Don't think support is the correct word?

**Comment by joaomcteixeira** [comment]
Don't know. Really need your help with the proper wording.

**Review by amjjbonvin — APPROVED** [review]
Made a few edits. Check it out

**Comment by joaomcteixeira** [comment]
Sounds perfect!

**Pull request merged**
