### PR TITLE
Add tool to identify CNS script dependencies

### LINKED ISSUE #42: Re-implement CNS-dependency finder script
In version alpha we had part of the code that would scan the `.cns` script and return its dependency tree up to 5 levels of complexity, this was used to compose the `.inp` script that would be executed by CNS, adding the script to relevant tags RUN, @@, etc.

 The dependency tree can get quite complex since there are many nested calls:

```
mainscript.cns
  |_ script_A.cns
  |_ script_B.cns
    |_ script_B1.cns
  |_ script_C.cns
    |_ script_C1.cns
      |_ script_C1.1.cns
        |_ script_C1.1.1
      |_ script_C1.2.cns
    |_ script C2.cns 
```
      
This part of the code is missing in the `main` branch, we should re-implement it as a tool to help us remove unnecessary CNS scripts from the core modules.

### PR DESCRIPTION
**Pull request by rvhonorato**
This PR implements a tool to help us clean the CNS dependencies in the HADDOCK core modules and closes #42. It takes the main CNS script as input and the production `protocols` directory; Ex:

```
$  python tools/cns_dependency_tree.py src/haddock/modules/topology/cns/generate-topology.cns /Users/rodrigo/repos/haddock24/protocols 
[27/07/2021 11:27:21] L41 INFO - Protocols directory: /Users/rodrigo/repos/haddock24/protocols
[27/07/2021 11:27:21] L42 INFO - Retrieving dependencies of /Users/rodrigo/repos/haddock3/src/haddock/modules/topology/cns/generate-topology.cns
[27/07/2021 11:27:21] L47 INFO - First level dependencies: 9
[27/07/2021 11:27:21] L49 INFO - Looking for deeper dependencies
[27/07/2021 11:27:21] L76 INFO - Total dependencies found: 10
[27/07/2021 11:27:21] L78 INFO - generate-topology.cns depends on: patch-types-cg.cns patch-bb-cg.cns build-missing.cns prot_break.cns dna_break.cns covalheme.cns coval-ace-cys.cns auto-his.cns flex_segment_back.cns flexauto-neighbors.cns
```

This script is not very pretty but we can work on it later. :)

### CODE REVIEW

**Comment by joaomcteixeira** [comment]
That looks a nice idea. But we should make it part of the haddock CLI tools, not a simple script. Let me work on that since I pulled #28 .

**Comment by joaomcteixeira** [comment]
Question: why the script needs the `/Users/rodrigo/repos/haddock24/protocols` ? Is that because the `haddock24/protocols` is planned to be transferred to haddock3 but it is not yet here?

Will this dependency on HADDOCK24 disappear after #41 ? If that is so, maybe that second argument can be a fixed folder within haddock3 folder structure.


It would be nice to have the output also as you suggested on #42 :wink: , looks much prettier.

**Comment by rvhonorato** [comment]
> Question: why the script needs the `/Users/rodrigo/repos/haddock24/protocols` ?

Because this is where the CNS protocols are, haddock3 is building on top of it.

> Will this dependency on HADDOCK24 disappear after #41 ? If that is so, maybe that second argument can be a fixed folder within haddock3 folder structure.

I'm afraid we will only keep relying on the production version (either 2.4 or 2.5) for a long time since it has many features that need to be implemented here; both ones that are already there as well as other that are being implement continuously.

**Comment by amjjbonvin** [comment]
We should start a haddock3 CNS protocol directory

**Comment by rvhonorato** [comment]
Closing this one since I already used this script to implement the core modules, we don't need to have it in the repository anymore.

**Pull request closed without merging**
